# Generated by Django 6.1 on 2026-08-31 16:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('tartib', models.PositiveSmallIntegerField(default=0)),
                ('faolmi', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['tartib', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('ism', models.CharField(max_length=100, verbose_name='Ism')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='Username')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon raqam')),
                ('bloklangan', models.BooleanField(default=False)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faolmi', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('yangilangan', models.DateTimeField(auto_now=True)),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
            options={
                'verbose_name': 'Savat',
                'verbose_name_plural': 'Savatlar',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Taom nomi')),
                ('tavsif', models.TextField(blank=True, verbose_name='Tavsi')),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="Narx (so'm)")),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='Taomlar/', verbose_name='Rasm')),
                ('tayyorlash_vaqti', models.PositiveSmallIntegerField(default=15, verbose_name='Taom tayyorlash vaqti(daq)')),
                ('faolmi', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('yangilasgan', models.DateTimeField(auto_now=True)),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Taomlar', to='main.category')),
            ],
            options={
                'verbose_name': 'Taom',
                'verbose_name_plural': 'Taomlar',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Miqdor')),
                ('qoshilgan', models.DateTimeField(auto_now_add=True)),
                ('savat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Qatorlar', to='main.cart')),
                ('taom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dish', verbose_name='Taom')),
            ],
            options={
                'verbose_name': 'Savat Qatori',
                'verbose_name_plural': 'Savat Qatorlari',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqam', models.CharField(db_index=True, max_length=16, unique=True)),
                ('holat', models.CharField(choices=[('yangi', 'Yangi'), ('tayyorlanmoqda', 'Tayyorlanmoqda'), ('tayyor', 'Tayyor'), ('berildi', 'Berildi'), ('yetkazildi', 'Yetkazildi'), ('bekor_qilindi', 'Bekor qilindi')], db_index=True, default='Yangi', max_length=20)),
                ('yetkazish_turi', models.CharField(choices=[('stol', 'Stolda'), ('manzil', 'Yetkazib berish')], max_length=10, verbose_name='Yetgazish turi')),
                ('stol_raqami', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Stol raaqami')),
                ('manzil', models.CharField(blank=True, max_length=300, verbose_name='Manzil')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('jami_summa', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami summa')),
                ('yetkazish_narxi', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Yetkazish narxi')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('tayyor_vaqti', models.DateTimeField(blank=True, null=True, verbose_name='Tayyor vaqti ')),
                ('yopingan_vaqti', models.DateTimeField(blank=True, null=True, verbose_name='Yopilgan vaqati')),
                ('bekor_sababi', models.CharField(blank=True, max_length=300, verbose_name='Bekor sababi')),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taom_nomi', models.CharField(max_length=120, verbose_name='Taom nomi (Nusxa)')),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dona narxi (Nusxa)')),
                ('miqdor', models.PositiveSmallIntegerField(verbose_name='Miqdor')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Summa')),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qatorlar', to='main.order', verbose_name='Buyurtma')),
                ('taom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyurtma_qatorlari', to='main.dish', verbose_name='Taom')),
            ],
            options={
                'verbose_name': 'Buyurtma Qatori',
                'verbose_name_plural': 'Buyurtma Qatorlari',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eski_holat', models.CharField(max_length=20, verbose_name='Eski holat')),
                ('yangi_holat', models.CharField(max_length=20, verbose_name='Yangi holat')),
                ('vaqt', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarix', to='main.order', verbose_name='Buyurtma')),
                ('kim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan')),
            ],
            options={
                'verbose_name': 'Buyurtma Holati Tarixi',
                'verbose_name_plural': 'Buyurtma Holatlari Tarixi',
            },
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('faolmi', True)), fields=('mijoz',), name='bitta_faol_savat'),
        ),
        migrations.AlterUniqueTogether(
            name='dish',
            unique_together={('kategoriya', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('savat', 'taom')},
        ),
    ]
