# Generated by Django 6.1 on 2026-09-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='tayyorlanish_vaqti',
            field=models.IntegerField(default=15),
        ),
    ]
